name: Testing on pull request
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '23 .x'
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
      - name: Run tests
          run yarn test
